### ISSUE TITLE
Pillow: AttributeError: 'list' object has no attribute '__array_interface__'

### ISSUE THREAD

**Issue by loguntsov** [martinchristen/pyRT#19]
When i'm trying start examples i gets
```
python3 01_drawlines.py 

Traceback (most recent call last):
  File "01_drawlines.py", line 18, in <module>
    image.save("01.png")
  File "/usr/local/lib/python3.6/dist-packages/pyrt-0.1.0-py3.6.egg/pyrt/renderer/rgbimage.py", line 59, in save
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2421, in fromarray
    arr = obj.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'
```

Can it be because i'm using Pillow library version of Version: 5.1.0

Thanks.

**Comment by martinchristen** [comment]
do you have numpy installed ?

**Comment by loguntsov** [comment]
It was without numpy installed. It works right now.
Could you make requirements.txt file with all requirements ? 

Thanks.
